name: Gipidi review
on:
    pull_request:
      types: [opened, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
    code_review_job:
        runs-on: ubuntu-latest
        name: ChatGPT Code Review
        steps:
        - uses: coderabbitai/ai-pr-reviewer@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          with:
            debug: true
            review_simple_changes: false
            review_comment_lgtm: false